;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Skill.Parry",NewTagName="Character.Event.Skill.Parry")
+GameplayTagRedirects=(OldTagName="Event.AI.Comba",NewTagName="Event.AI.Combat")
+GameplayTagList=(Tag="Character.State.Buff.SuperArmor",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Attack.Ranged",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Vault",DevComment="파쿠르/볼팅 능력 실행 트리거")
+GameplayTagList=(Tag="Character.Event.CheckCombo",DevComment="")
+GameplayTagList=(Tag="Character.Event.Death",DevComment="")
+GameplayTagList=(Tag="Character.Event.HitReact",DevComment="")
+GameplayTagList=(Tag="Character.Event.Skill.Parry",DevComment="")
+GameplayTagList=(Tag="Character.State.Action.Grappling",DevComment="그래플링 이동 진행 중")
+GameplayTagList=(Tag="Character.State.Action.Melee",DevComment="근접 공격 콤보 진행 중")
+GameplayTagList=(Tag="Character.State.Action.Ranged",DevComment="원거리 사격 진행 중")
+GameplayTagList=(Tag="Character.State.Action.Vaulting",DevComment="파쿠르/볼팅 액션 진행 중")
+GameplayTagList=(Tag="Character.State.AI.Chase",DevComment="AI 추적 상태 (플레이어 발견)")
+GameplayTagList=(Tag="Character.State.AI.Idle",DevComment="AI 대기 상태")
+GameplayTagList=(Tag="Character.State.AI.Investigate",DevComment="AI 의심/수색 상태 (소리를 듣거나 시야에서 놓침)")
+GameplayTagList=(Tag="Character.State.AI.Patrol",DevComment="AI 순찰 상태")
+GameplayTagList=(Tag="Character.State.Debuff.HitReact",DevComment="일반 피격 경직 상태")
+GameplayTagList=(Tag="Character.State.Debuff.Stun",DevComment="기절/행동 불가 상태")
+GameplayTagList=(Tag="Character.State.IsDead",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.Sliding",DevComment="슬라이딩 중")
+GameplayTagList=(Tag="Character.State.Movement.WallRunning",DevComment="벽 타기 중")
+GameplayTagList=(Tag="Character.State.Parry.Active",DevComment="")
+GameplayTagList=(Tag="Event.AI.Combat",DevComment="")
+GameplayTagList=(Tag="Event.AI.Combat.Chase",DevComment="")
+GameplayTagList=(Tag="Event.AI.Idle",DevComment="")
+GameplayTagList=(Tag="Event.AI.Investigate",DevComment="State Tree에 수색 상태 진입 명령 전송")
+GameplayTagList=(Tag="Event.AI.Stun",DevComment="State Tree에 기절 상태 진입 명령 전송")
+GameplayTagList=(Tag="Event.Melee.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Ranged.Fire",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Ammo.Pistol",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Ammo.Rifle",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Reload",DevComment="")

