;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Skill.Parry",NewTagName="Character.Event.Skill.Parry")
+GameplayTagList=(Tag="Character.Event.CheckCombo",DevComment="")
+GameplayTagList=(Tag="Character.Event.Death",DevComment="")
+GameplayTagList=(Tag="Character.Event.HitReact",DevComment="")
+GameplayTagList=(Tag="Character.Event.Skill.Parry",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDead",DevComment="")
+GameplayTagList=(Tag="Character.State.Parry.Active",DevComment="")
+GameplayTagList=(Tag="Event.Melee.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Ranged.Fire",DevComment="")

